name: app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  table_calendar: ^3.0.0
  flutter_event_calendar: ^1.0.0
  flutter_barcode_scanner: ^2.0.0
  cupertino_icons: ^1.0.2
  google_mlkit_text_recognition: ^0.4.0
  permission_handler: ^10.2.0
  camera: ^0.10.0+4
  google_ml_kit: ^0.6.0
  get: ^4.6.5
  path: ^1.8.3
  sqflite: ^2.3.0
  flutter_local_notifications: ^5.0.0
  timezone: ^0.7.0
  flutter_timezone: ^1.0.8
  cron: ^0.6.0
  dio: ^5.4.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  connectivity: ^3.0.6
  mockito: ^5.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/